<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0hhL6ra' shared service.

return $this->privates['.service_locator.0hhL6ra'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('realisateurRepository' => function (): \App\Repository\RealisateurRepository {
    return ($this->privates['App\Repository\RealisateurRepository'] ?? $this->load('getRealisateurRepositoryService.php'));
}));
