<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DYPBHGU' shared service.

return $this->privates['.service_locator.DYPBHGU'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('filmRepository' => function (): \App\Repository\FilmRepository {
    return ($this->privates['App\Repository\FilmRepository'] ?? $this->load('getFilmRepositoryService.php'));
}));
