<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFp2I3If\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFp2I3If/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFp2I3If.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFp2I3If\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFp2I3If\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fp2I3If',
    'container.build_id' => '2a5361ee',
    'container.build_time' => 1544379889,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFp2I3If');
