<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBLm5t8d\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBLm5t8d/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBLm5t8d.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBLm5t8d\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBLm5t8d\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BLm5t8d',
    'container.build_id' => '220383bf',
    'container.build_time' => 1543823776,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBLm5t8d');
