<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCzyCFxT\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCzyCFxT/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCzyCFxT.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCzyCFxT\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCzyCFxT\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CzyCFxT',
    'container.build_id' => '3c32a60d',
    'container.build_time' => 1542028137,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCzyCFxT');
